---
- name: update all packages to the latest version
  apt: >
    upgrade=dist
    update_cache=yes
    cache_valid_time=1

- apt: "pkg={{item}} state=latest force=yes"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev

- name: generating {{locale}} file
  locale_gen: name={{locale}} state=present

- name: setting locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
